Repository TeamYukgaejang/plus-project, pull requests merged in 2025-09, with the labels that each got.

#6 [FEATURE] user : 기초 구조 설계
  build.gradle
  src/main/java/org/example/plusproject/common/config/SecurityConfig.java
  src/main/java/org/example/plusproject/common/entity/BaseRemovableEntity.java
  src/main/java/org/example/plusproject/domain/user/controller/UserController.java
  src/main/java/org/example/plusproject/domain/user/dto/request/SignUpRequestDto.java
  src/main/java/org/example/plusproject/domain/user/dto/response/SignUpResponseDto.java
  src/main/java/org/example/plusproject/domain/user/entity/User.java
  src/main/java/org/example/plusproject/domain/user/repository/UserRepository.java
  src/main/java/org/example/plusproject/domain/user/service/command/UserCommandService.java
  src/main/java/org/example/plusproject/domain/user/service/command/UserCommandServiceImpl.java
  src/main/resources/application.yml
Labels: ✨ feature

#17 [CHORE] basic: ci.yml update
  .github/workflows/ci.yml
Labels: 🧹 chore

#15 [FEATURE] user : JWT 기반 로그인 기능 구현
  src/main/java/org/example/plusproject/common/jwt/JwtUtil.java
  src/main/java/org/example/plusproject/domain/user/controller/UserController.java
  src/main/java/org/example/plusproject/domain/user/dto/request/LoginRequestDto.java
  src/main/java/org/example/plusproject/domain/user/service/command/UserCommandService.java
  src/main/java/org/example/plusproject/domain/user/service/command/UserCommandServiceImpl.java
  src/main/resources/application.yml
Labels: ✨ feature

#36 [REFACTOR] common: API 응답 및 에러 코드 구조 리팩토링
  src/main/java/org/example/plusproject/common/consts/CommonErrorCode.java
  src/main/java/org/example/plusproject/common/consts/ErrorCode.java
  src/main/java/org/example/plusproject/common/consts/SuccessCode.java
  src/main/java/org/example/plusproject/domain/search/exception/SearchErrorCode.java
  src/main/java/org/example/plusproject/domain/user/controller/UserController.java
  src/main/java/org/example/plusproject/domain/user/service/command/UserCommandService.java
  src/main/java/org/example/plusproject/domain/user/service/command/UserCommandServiceImpl.java
  src/test/java/org/example/plusproject/PlusProjectApplicationTests.java
  src/test/java/org/example/plusproject/domain/search/service/commandservice/SearchCommandServiceTest.java
  src/test/resources/application-test.yml
Labels: 🔨 refactor

#37 [FEATURE] security: JWT 인증 필터 구현
  src/main/java/org/example/plusproject/common/config/SecurityConfig.java
  src/main/java/org/example/plusproject/common/jwt/JwtAuthenticationFilter.java
  src/main/java/org/example/plusproject/common/jwt/JwtUtil.java
  src/main/java/org/example/plusproject/common/security/JwtAuthenticationToken.java
  src/main/java/org/example/plusproject/domain/user/controller/UserController.java
  src/main/java/org/example/plusproject/domain/user/dto/security/AuthUser.java
  src/main/java/org/example/plusproject/domain/user/service/command/UserCommandServiceImpl.java
Labels: ✨ feature

#39 [FEATURE] user: 회원 탈퇴 로직 구현
  src/main/java/org/example/plusproject/domain/user/controller/UserController.java
  src/main/java/org/example/plusproject/domain/user/service/command/UserCommandService.java
  src/main/java/org/example/plusproject/domain/user/service/command/UserCommandServiceImpl.java
Labels: ✨ feature

#40 [FEATURE] product: 상품 등록 API 구현
  src/main/java/org/example/plusproject/common/consts/ErrorCode.java
  src/main/java/org/example/plusproject/common/consts/SuccessCode.java
  src/main/java/org/example/plusproject/domain/product/controller/AdminProductController.java
  src/main/java/org/example/plusproject/domain/product/controller/ProductController.java
  src/main/java/org/example/plusproject/domain/product/dto/request/ProductCreateRequest.java
  src/main/java/org/example/plusproject/domain/product/dto/response/ProductResponse.java
  src/main/java/org/example/plusproject/domain/product/entity/Product.java
  src/main/java/org/example/plusproject/domain/product/service/command/ProductCommandService.java
  src/main/java/org/example/plusproject/domain/product/service/command/ProductCommandServiceImpl.java
  src/main/java/org/example/plusproject/domain/product/service/query/ProductQueryService.java
  src/main/java/org/example/plusproject/domain/product/service/query/ProductQueryServiceImpl.java
Labels: ✨ feature

#49 [FEATURE] product: 상품 정보 수정 API 구현
  src/main/java/org/example/plusproject/domain/product/controller/AdminProductController.java
  src/main/java/org/example/plusproject/domain/product/dto/request/ProductRequest.java
  src/main/java/org/example/plusproject/domain/product/entity/Product.java
  src/main/java/org/example/plusproject/domain/product/exception/ProductSuccessCode.java
  src/main/java/org/example/plusproject/domain/product/service/command/ProductCommandService.java
  src/main/java/org/example/plusproject/domain/product/service/command/ProductCommandServiceImpl.java
  src/main/java/org/example/plusproject/domain/product/service/query/ProductQueryServiceImpl.java
Labels: ✨ feature

#48 Feature/search/45
  build.gradle
  src/main/java/org/example/plusproject/PlusProjectApplication.java
  src/main/java/org/example/plusproject/common/config/CacheConfig.java
  src/main/java/org/example/plusproject/domain/search/controller/SearchController.java
  src/main/java/org/example/plusproject/domain/search/entity/SearchKeyword.java
  src/main/java/org/example/plusproject/domain/search/service/queryservice/SearchQueryService.java
  src/main/java/org/example/plusproject/domain/user/entity/User.java
  src/test/java/org/example/plusproject/domain/search/service/commandservice/SearchCommandServiceTest.java
  src/test/java/org/example/plusproject/domain/search/service/queryservice/SearchQueryServiceTest.java
  src/test/java/org/example/plusproject/domain/search/service/queryservice/SearchQueryServiceV2Test.java
Labels: ✨ feature

#52 [FEATURE] category: 카테고리 생성 API 구현
  src/main/java/org/example/plusproject/domain/category/controller/CategoryController.java
  src/main/java/org/example/plusproject/domain/category/dto/request/CategoryCreateRequest.java
  src/main/java/org/example/plusproject/domain/category/dto/response/CategoryResponse.java
  src/main/java/org/example/plusproject/domain/category/entity/Category.java
  src/main/java/org/example/plusproject/domain/category/exception/CategoryErrorCode.java
  src/main/java/org/example/plusproject/domain/category/exception/CategoryException.java
  src/main/java/org/example/plusproject/domain/category/repository/CategoryRepository.java
  src/main/java/org/example/plusproject/domain/category/service/command/CategoryCommandService.java
  src/main/java/org/example/plusproject/domain/category/service/command/CategoryCommandServiceImpl.java
Labels: ✨ feature

#58 [FEATURE] category: 카테고리 수정 API 구현
  src/main/java/org/example/plusproject/domain/category/controller/AdminCategoryController.java
  src/main/java/org/example/plusproject/domain/category/controller/CategoryController.java
  src/main/java/org/example/plusproject/domain/category/dto/request/CategoryUpdateRequest.java
  src/main/java/org/example/plusproject/domain/category/dto/response/CategoryResponse.java
  src/main/java/org/example/plusproject/domain/category/entity/Category.java
  src/main/java/org/example/plusproject/domain/category/exception/CategorySuccessCode.java
  src/main/java/org/example/plusproject/domain/category/repository/CategoryRepository.java
  src/main/java/org/example/plusproject/domain/category/service/command/CategoryCommandService.java
  src/main/java/org/example/plusproject/domain/category/service/command/CategoryCommandServiceImpl.java
Labels: ✨ feature

#59 [FEATURE] category: 카테고리 삭제 API 구현
  src/main/java/org/example/plusproject/domain/category/controller/AdminCategoryController.java
  src/main/java/org/example/plusproject/domain/category/controller/CategoryController.java
  src/main/java/org/example/plusproject/domain/category/dto/response/CategorySummaryResponse.java
  src/main/java/org/example/plusproject/domain/category/exception/CategorySuccessCode.java
  src/main/java/org/example/plusproject/domain/category/repository/CategoryRepository.java
  src/main/java/org/example/plusproject/domain/category/service/command/CategoryCommandService.java
  src/main/java/org/example/plusproject/domain/category/service/command/CategoryCommandServiceImpl.java
  src/main/java/org/example/plusproject/domain/category/service/query/CategoryQueryService.java
  src/main/java/org/example/plusproject/domain/category/service/query/CategoryQueryServiceImpl.java
Labels: ✨ feature

#62 [FEATURE] user: User 도메인 서비스 분리 및 커스텀 예외 적용
  src/main/java/org/example/plusproject/common/config/SecurityConfig.java
  src/main/java/org/example/plusproject/domain/user/exception/EmailDuplicatedException.java
  src/main/java/org/example/plusproject/domain/user/exception/LoginFailedException.java
  src/main/java/org/example/plusproject/domain/user/exception/NicknameDuplicatedException.java
  src/main/java/org/example/plusproject/domain/user/exception/UserErrorCode.java
  src/main/java/org/example/plusproject/domain/user/exception/UserNotFoundException.java
  src/main/java/org/example/plusproject/domain/user/service/command/UserCommandServiceImpl.java
  src/main/java/org/example/plusproject/domain/user/service/query/UserQueryService.java
  src/main/java/org/example/plusproject/domain/user/service/query/UserQueryServiceImpl.java
  src/test/java/org/example/plusproject/domain/user/service/command/UserCommandServiceImplTest.java
Labels: ✨ feature

#65 [FEATURE] user: 로그아웃 기능 구현
  src/main/java/org/example/plusproject/domain/user/controller/UserController.java
  src/main/java/org/example/plusproject/domain/user/exception/UserSuccessCode.java
Labels: ✨ feature

#68 [REFACTOR]: user: 서버 측 로그아웃 기능 구현 (Redis 토큰 블랙리스트)
  build.gradle
  src/main/java/org/example/plusproject/common/jwt/JwtAuthenticationFilter.java
  src/main/java/org/example/plusproject/domain/user/controller/UserController.java
  src/main/java/org/example/plusproject/domain/user/service/command/UserCommandService.java
  src/main/java/org/example/plusproject/domain/user/service/command/UserCommandServiceImpl.java
  src/test/java/org/example/plusproject/domain/user/service/command/UserCommandServiceImplTest.java
Labels: 🔨 refactor

#70 fix : [user] 로그아웃 인증 관련 오류 수정
  src/main/java/org/example/plusproject/common/config/SecurityConfig.java
Labels: ✨ feature

#73 [FIX] product: 상품 연관관계 매핑 후 생긴 오류 해결
  dump.rdb
  src/main/java/org/example/plusproject/common/config/SecurityConfig.java
  src/main/java/org/example/plusproject/domain/category/controller/AdminCategoryController.java
  src/main/java/org/example/plusproject/domain/category/service/command/CategoryCommandServiceImpl.java
  src/main/java/org/example/plusproject/domain/product/controller/ProductController.java
  src/main/java/org/example/plusproject/domain/product/dto/request/ProductRequest.java
  src/main/java/org/example/plusproject/domain/product/dto/response/ProductResponse.java
  src/main/java/org/example/plusproject/domain/product/entity/Product.java
  src/main/java/org/example/plusproject/domain/product/repository/ProductRepository.java
  src/main/java/org/example/plusproject/domain/product/service/command/ProductCommandServiceImpl.java
Labels: ✨ feature, 🐞 bug, 🎨 style
